modLoader="javafml" #mandatory

loaderVersion="[36,)"

license="All rights reserved"

[[mods]] #mandatory

modId="piscine" #mandatory

version= "v1.0.0" # "${file.jarVersion}" mandatory

displayName="Piscine" #mandatory

# logoFile="examplemod.png" #optional

credits="Thanks to Peeko & SirReadsALot for making this mod" #optional

authors="SirReadsALot & Peeko" #optional

description='''
    A funny fish mod.
'''

[[dependencies.examplemod]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[36,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
